### ISSUE TITLE
http://get.acralyzer.com/distrib-acralyzer not working

### ISSUE THREAD

**Issue by xlc1540697096** [ACRA/acralyzer#136] opened 2017-12-27 03:41 UTC
http 502, slow, help me

**Comment by F43nd1r** [comment] 2017-12-27 13:32
Duplicate of #133

**Closed by F43nd1r** 2017-12-27 13:32 UTC

**Comment by Fahriya** [comment] 2018-04-04 05:33
I can not replicate db from http://get.acralyzer.com/distrib-acra-storage , always returns   {http_error_code,503,<<"GET http://get.acralyzer.com/distrib-acra-storage/">>}
