### ISSUE TITLE
Can't replicate acralyzer 

### ISSUE THREAD

**Issue by amineDev** [ACRA/acralyzer#137] opened 2018-01-18 17:01 UTC
Hello,

Im using couchDB 2 and trying to replicate the acra-storage and acralyzer but im getting the following error :

```
Retrying GET request to http://get.acralyzer.com/distrib-acralyzer/ in 0.25 seconds due to error {conn_failed,{error,etimedout}}

Retrying GET request to http://get.acralyzer.com/distrib-acra-storage/ in 0.5 seconds due to error {conn_failed,{error,etimedout}}

```

Thanks for help

Best regards

**Comment by F43nd1r** [comment] 2018-01-18 17:13
Duplicate of #133

**Closed by F43nd1r** 2018-01-18 17:13 UTC
